apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: auth-nate
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1p6Q0NBVThDQVFBd0lqRU5NQXNHQTFVRUF3d0VibUYwWlRFUk1BOEdBMVVFQ2d3SVkzSmhibVJsYkd3dwpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ3ZHOWE2RTQrbFpBNVpZN2l6QzBkCjkySmxMMy9DYUpVU3BmK1BzbjFDZnQyNFNmV0N5KzBFSVZvbUV5SlIwVFhlWVdBRzdwWUJtTzJqZ2k3dktpNkgKKzVYUGI1ck4vZmd4OGthU1FKWHBmS25paW5kL2lvUTgwa0Q1NExhcUQ4b3hYb1YwQllETjM5ejFRYUtrc2J5cApnVW4welBLVjJ6YlQ1SG9hUnhlM2trWktiQ1UwZG84TytiV21BWFovcUpvUmxLOWwrc2ZhMzNQcE5YbnUycGhsCkJvNVlWVmNka2l2UzJ1M0tkaHpRV25QUGZjRVlSTmprVFlrWmQ1Ylp6UW9YeWdzNjlrZzNDNFdaaXlQUzdVMDEKKzRuNTY3akZnbkVQcHBlWG5YQVNRY0FwRU5ZSDNpbWY3OGE5a3c4NEZvaDRIWjZKNFQrVEpJZFhNdUxoQzJyegpBZ01CQUFHZ0FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYUmU3aVpiSk52Nkd1UWNIUForN0tqcTQvbHQvClRIT1BITjBHY0M0VDkzVWJlbjRLMGRxZUI3QStFaThxWlVDeHJBcjlwQmpBT1ZRTWpzdkdiZ1dZZ0E2M21vRnEKbEFqZHVqQUE4SkFyWXVYd1pSeENmaVJzeDdYUTVUL2d0VUw1dWFGWFI3NkRWMFB0eU9zUzdqRWNzMVF1aTRlaApLaUFPUGJkR3BQYmJCSTg3Tm1IVFNURXdhVFE4OHJZMHNFdlkrZjhlWnI1OFpmVm11YmVBY1k4ZjlibVVjejdFCkwzNExHWkxIV3laSXFvRkRydXEwZEViU3RoL29tUlZjUFRUT01nU1gzWHRkVjg4ZlVmT2xpM0pxQklCRmJzczgKbFpmVGZvN1Q4NHBaNmU1eVRaZ1FoU2ZuVVp5QmFjLytMbXAwR0tsd05IMStOelpVWnhGa0pLamNIdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth