# renew_before_expiry = 30 days
version = 1.17.0.dev0
archive_dir = /etc/letsencrypt/archive/*.crandell.us
cert = /etc/letsencrypt/live/*.crandell.us/cert.pem
privkey = /etc/letsencrypt/live/*.crandell.us/privkey.pem
chain = /etc/letsencrypt/live/*.crandell.us/chain.pem
fullchain = /etc/letsencrypt/live/*.crandell.us/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = bc57472297b036bce1e03432b55a2861
authenticator = certbot-dns-joker:dns-joker
server = https://acme-v02.api.letsencrypt.org/directory
certbot_dns_joker:dns_joker_propagation_seconds = 120
certbot_dns_joker:dns_joker_credentials = /etc/letsencrypt/secrets/crandell.us.ini
