
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.1.2.220

zoneminder:
  - host: zm-1.crandell.us
    path: /zm/
    path_zms: /zm/cgi-bin/nph-zms
    ssl: false
    verify_ssl: false
    #username: YOUR_USERNAME
    #password: YOUR_PASSWORD
