DBHost=localhost
DBName=zabbix
DBUser=zabbix
DBPassword=Chair9899
StartPollers=8
StartIPMIPollers=0
StartPollersUnreachable=2
StartTrappers=3
StartPingers=10
StartDiscoverers=1
StartAlerters=1
ExternalScripts=/usr/lib/zabbix/externalscripts
StartProxyPollers=0
