[global]
security = user
map to guest = Bad User
username map = /etc/samba/smbusers
usershare path =
netbios name = videos

[videos]
vfs objects = ceph
path = /libraries/videos/
kernel share modes = no
public = yes
read only = no
guest only = yes
ceph:user_id = compute
ceph:config_file = /etc/ceph/ceph.conf

[zoneminder]
vfs objects = ceph
path = /libraries/zoneminder/events/
kernel share modes = no
public = yes
read only = no
guest only = yes
ceph:user_id = compute
ceph:config_file = /etc/ceph/ceph.conf
